apiVersion: v1
kind: Secret
metadata:
  name: docker-login
  namespace: {{ .Values.namespace }}
  annotations:
    tekton.dev/docker-0: https://docker.io
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.dockerLogin.username }}
  password: {{ .Values.dockerLogin.password }}
