apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-account
  namespace: {{ .Values.namespace }}
secrets:
 - name: docker-login
---

apiVersion: v1
kind: Secret
metadata:
  name: kube-api-secret
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: pipeline-account
type: kubernetes.io/service-account-token

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["get", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-role
subjects:
- kind: ServiceAccount
  name: pipeline-account
