apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rfn-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
spec:
  rules:
    - host: {{ quote .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
             service:
              name: {{ quote .Values.ingress.serviceName }}
              port:
               number: {{ .Values.ingress.servicePort }}

